### ISSUE TITLE
Dropdown value falling outside the box

### ISSUE THREAD

**Issue by APelekh** [angular-ui/ui-select#1146]
I have a problem with displaying the chosen dropdown value. Please screenshot below:

![image](https://cloud.githubusercontent.com/assets/10589188/9262216/77ed81e8-41d0-11e5-9820-a3420e9b571c.png)

As you see, the value is longer than the box itself and it is falling outside. However, when I open the dropdown, value is displayed properly:

![image](https://cloud.githubusercontent.com/assets/10589188/9262317/3daf6946-41d1-11e5-8000-334526926334.png)

I did my best to find related issues, but I couldn't find any. Please advise if it is a problem with ui select or bootstrap css theme. My code is below.

```html
<ui-select ng-model="item.id" theme="bootstrap">
   <ui-select-match allow-clear="true" placeholder="Select or type in">{{$select.selected}}</ui-select-match>
     <ui-select-choices repeat="item in itemList | filter: $select.search">
          <div ng-bind-html="item | highlight: $select.search"></div>
     </ui-select-choices> 
</ui-select>
```

Thanks

**Comment by awerlang** [comment]
Duplicate of #689 and #933

Checkout any of those for solutions.

**Comment by APelekh** [comment]
Got it work with 

```css
.ui-select-match-text{
  width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 40px;
}
.ui-select-toggle > .btn.btn-link {
  margin-right: 10px;
  top: 6px;
  position: absolute;
  right: 10px;
}
```
