### ISSUE TITLE
add ellipsis for toggled text

### ISSUE THREAD

**Issue by gouroujo** [angular-ui/ui-select#1629]
with bootstrap:

I've added the following css classes to add text ellipsis:
```css
.ui-select-match-text {
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
  max-width: 90%;
}
.ui-select-toggle > .btn-link {
  position: absolute;
  right: 5px;
}
```
