### ISSUE TITLE
Input box is hidden with search-enabled="false" with Bootstrap theme

### ISSUE THREAD

**Issue by cdjackson** [angular-ui/ui-select#453]
With the Bootstrap theme, if I add the search-enabled="false" attribute, when the dropdown is clicked, the input box is hidden. This seems strange behaviour - maybe it's intended, but if so, can it be disabled? I want to keep the input box, but just not accept input (similar to how the Selectize theme works).
Aside from being a nuisance in itself, it also causes the parent to resize when the dropdown is opened.

**Comment by gen4sp** [comment]
+1 unexpected and unable to fix without fork
Please, remove it or make optional.

**Comment by donbobka** [comment]
:+1:

**Comment by chuckrea** [comment]
+1 Just happened to me as well. Very odd.

**Comment by brentmiller** [comment]
I am experiencing the same issue but with the select2 theme. Thus the issue isn't limited to the bootstrap theme.

**Comment by jedimindtrix9** [comment]
Yes, this is weird. I set a placeholder for default text ie (-select an option-). I am using the selectize theme: Two things I've noticed...1. If I switch the theme to bootstrap, the placeholder option will display. The other option was to set search-enabled to "false". Any help here would be greatly appreciated.

**Comment by seinavco** [comment]
+1

Please fix this issue.

**Comment by SamPlacette** [comment]
+1 This is affecting me as well. I am working around the problem for now by specifying placeholder text using :before pseudo-selector.

**Comment by sagivf** [comment]
+1 It would also be desirable for this to work with the "selectize" theme.
```css
.ui-select-container[search-enabled=false] .ui-select-match.ng-hide {
  display: inline-block !important;
}
.ui-select-container[search-enabled=false] .ui-select-match .text-muted.ng-hide {
  display: inline !important;
}
.ui-select-container[search-enabled=false].ng-dirty .ui-select-match .text-muted.ng-hide {
  display: none !important;
}
```
Thanks @SamPlacette.
