### ISSUE TITLE
Input Width not 100%

### ISSUE THREAD

**Issue by erslater** [angular-ui/ui-select#533]
I have a multi select inside a bootstrap tab page and the search input is only 10px wide when it first displays. 

![beforefocus](https://cloud.githubusercontent.com/assets/3407052/5495663/7b8ebc40-86cd-11e4-8159-d304a5f08378.PNG)

After clicking on the tab that the multi select appears on the width will expand to 100% once focus is placed on any of the controls in the form.

![afterfocus](https://cloud.githubusercontent.com/assets/3407052/5495667/835f45d4-86cd-11e4-9ab0-c3eeff1ae9bd.PNG)

**Comment by havenchyk** [comment]
@erslater, could you provide demo?

**Comment by PowerKiKi** [comment]
Here is a Plunker updated to latest versions of everything and demonstrating the issue: http://plnkr.co/edit/f6o1hxq1Yymc7Vv2oMHb?p=preview

As you can see removing ``ngAnimate`` avoid the issue. Unfortunately this is probably not an acceptable solution for real-world cases.

**Comment by rywhee** [comment]
Having the same issue here.... 

For now, in my scenario, was able to hack around the problem by tweaking the positioning of related elements. Of course the ui-select-container needs a height...

``` css
  .select2-choices {
    position: relative;
  }
  .ui-select-multiple input.ui-select-search {
    width: 100% !important;
    position: absolute;
  }
```
