### ISSUE TITLE
Styling matched text in choices

### ISSUE THREAD

**Issue by ilanbiala** [angular-ui/ui-select#538]
How can I use `.ui-select-highlight` to style the matched text in a choice?

**Comment by ilanbiala** [comment]
@brianfeister how can I do this?

**Comment by ilanbiala** [comment]
@brianfeister can this be done or does this need to be added in?

**Comment by brianfeister** [comment]
Currently we have:

```css
.ui-select-highlight {
  font-weight: bold;
}
```

So to style the text red instead of bold, you would just add the following to your own CSS (overriding ui-select's default)

```css
.ui-select-highlight {
  font-weight:normal;
  color: red;
}
```
