### ISSUE TITLE
Allow change the arrow

### ISSUE THREAD

**Issue by gerardp** [angular-ui/ui-select#594]
Add the ability to add an icon inside the input tag, for example instead of an arrow a magnifying glass like the example:

![expanding-css-input-field](https://cloud.githubusercontent.com/assets/168353/5815990/7c9e51bc-a09b-11e4-96f9-5011f73693e9.png)

**Comment by osales** [comment]
:+1:

**Comment by Misiu** [comment]
:+1:

**Comment by windmaomao** [comment]
or just hide it.

**Comment by wesleycho** [comment]
This is already possible on the user's side - at work we do exactly this, and even change the icon depending on the state.

Closing as a support issue.

**Comment by jaxspades** [comment]
@wesleycho Please provide an example as to how you can do this.

**Comment by MangeshPimpalkar** [comment]
👍

**Comment by ViieeS** [comment]
I've achieve this using style hack:

```scss
.ui-select-bootstrap.ui-select-loading-data .ui-select-toggle > .caret {
  margin-top: -9px;
  top: 50%;
  right: 25px;
  border: none;

  &:before {
    @extend .fa, .fa-spinner, .fa-spin;
  }
}
```

**Comment by ViieeS** [comment]
I've achieved this using a style hack:

```scss
.ui-select-bootstrap.ui-select-loading-data .ui-select-toggle > .caret {
  margin-top: -9px;
  top: 50%;
  right: 25px;
  border: none;

  &:before {
    @extend .fa, .fa-spinner, .fa-spin;
  }
}
```
