### ISSUE TITLE
Style for invalid input overrides Bootstrap style

### ISSUE THREAD

**Issue by AntiFreez** [angular-ui/ui-select#602]
```css
.ui-select-bootstrap.ng-dirty.ng-invalid > button.btn.ui-select-match {
   border-color: #D44950;
}
```
overrides 
```css
.has-error .form-control {
   border-color: #a94442;
}
```
