### ISSUE TITLE
Bootstrap theme: missing scrollbar on IE8

### ISSUE THREAD

**Issue by gillius** [angular-ui/ui-select#66]
On IE8, when the select dropdown is taller than the max-width, there is no scrollbar. This is due to a missing overflow-y style. In IE8, without the style, it acts as if overflow-y: hidden. Adding the following CSS fixes this problem.

``` css
.ui-select-bootstrap > .ui-select-choices {
    overflow-y: auto;
}
```

I also tested that latest Chrome and Firefox are not affected (they still show the scrollbar only when content is too tall).
