### ISSUE TITLE
Dropdown appears very small with Angular Mobile

### ISSUE THREAD

**Issue by Gillardo** [angular-ui/ui-select#729]
Select-UI works perfectly fine with normal bootstrap, but i have tried using it with Angular UI Mobile, which uses a slightly modified version of bootstrap.  it appears that the dropdowns do not appear correctly.  I added this css to my file and it fixes the problem.  Just thought i would put it here encase anyone else faces the same problem

```css
.ui-select-bootstrap > .dropdown-menu {
    display: none;
}

.ui-select-bootstrap.open > .dropdown-menu {
    display: block;
}
```
